# Generated by Django 3.2.16 on 2022-11-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='last_edited',
            field=models.DateField(auto_now=True),
        ),
    ]
