# Generated by Django 3.2.16 on 2022-11-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_reviews_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
