# Generated by Django 3.2.16 on 2022-12-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_direction_recipe_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Optionally upload an image', null=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(help_text='Place directions in <li></li>                                   tags'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='excerpt',
            field=models.TextField(help_text='Summary to display on recipe list.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='Place ingredients in <li></li>                                    tags'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='intro',
            field=models.TextField(help_text='Short introduction of the recipe. If                              using user submitted recipe, please remember to                              credit the user.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='outro',
            field=models.TextField(blank=True, help_text='Optional. A                              short outro for the recipe.', null=True),
        ),
        migrations.AlterField(
            model_name='submittedrecipe',
            name='notes',
            field=models.TextField(blank=True, help_text='Please include                              any notes or insights you would like included.', null=True),
        ),
    ]
