# Generated by Django 3.2.16 on 2022-12-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221211_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(help_text='Place directions in                                   &lt;li&gt;&lt;/li&gt; tags'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='Place ingredients in                                    &lt;li&gt;&lt;/li&gt; tags'),
        ),
    ]
