# Generated by Django 3.2.16 on 2022-11-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_helditems_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heldcart',
            name='hold_time_start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
