# Generated by Django 3.2.16 on 2022-11-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_heldcart_hold_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='helditems',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
