# Generated by Django 3.2.16 on 2022-11-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_helditems_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heldcart',
            name='cart_key',
            field=models.CharField(max_length=80),
        ),
    ]
