# Generated by Django 3.2.16 on 2022-11-25 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, help_text="Include a description for the                                    product's page.", null=True)),
                ('excerpt', models.TextField(blank=True, help_text='Include a                                brief summary of the product.', null=True)),
                ('ingredients', models.CharField(blank=True, help_text='For sauces, please include the                                    ingredients.', max_length=140, null=True)),
                ('growth_time', models.CharField(blank=True, help_text='For seeds, please include the                                    growth time to maturity.', max_length=140, null=True)),
                ('heat_level', models.CharField(blank=True, help_text="In scovilles or more generally                                   (eg 'hot') where appropriate.", max_length=140, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, help_text='If not added, will be                                   auto-generated from image.', null=True, upload_to='uploads/')),
                ('added_on', models.DateField(auto_now_add=True)),
                ('box_contents', models.ManyToManyField(blank=True, help_text='Add                                           products for seed and sauce boxes.', related_name='_products_product_box_contents_+', to='products.Product')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.category')),
            ],
            options={
                'ordering': ('name',),
                'get_latest_by': ('added_on',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='Default is 0.')),
                ('in_stock', models.BooleanField(default=False, help_text='Updates when current stock                                    updated.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Variants',
            },
            managers=[
                ('by_stock', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory'),
        ),
    ]
