# Generated by Django 3.2.16 on 2022-11-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
