# Generated by Django 3.2.16 on 2022-11-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='box_contents',
            field=models.ManyToManyField(blank=True, help_text='Add                                           products for seed and sauce boxes.', related_name='_products_product_box_contents_+', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.PositiveIntegerField(default=0, help_text='Default is 0.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text="Include a description for the                                    product's page.", null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Include a                                brief summary of the product.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='growth_time',
            field=models.CharField(blank=True, help_text='For seeds, please include the                                    growth time to maturity.', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='heat_level',
            field=models.CharField(blank=True, help_text="In scovilles or more generally                                   (eg 'hot') where appropriate.", max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False, help_text='Updates when current stock                                    updated.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.CharField(blank=True, help_text='For sauces, please include the                                    ingredients.', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='If not added, will be                                   auto-generated from image.', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(help_text='Must include at least one for                                       default price and size.', related_name='products', to='products.ProductVariant'),
        ),
    ]
