# Generated by Django 3.2.16 on 2022-11-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, help_text='Origin of the seeds.', max_length=80, null=True),
        ),
    ]
