# Generated by Django 3.2.16 on 2022-12-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='origin',
        ),
    ]
